# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class AcordoDetalheResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        AcordoDetalheResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'id_conta': 'int',
            'status_acordo': 'int',
            'valor_acordo': 'float',
            'data_acordo': 'str',
            'quantidade_parcelas': 'int',
            'saldo_atual_final': 'float',
            'dias_em_atraso': 'int',
            'status_conta': 'int',
            'assessoria_atual': 'str',
            'total_pagamentos': 'float',
            'data_vencimento_cobranca': 'str',
            'data_quebra_acordo': 'str',
            'valor_parcela1': 'float',
            'valor_parcela_n': 'float',
            'parcela_pedida': 'int',
            'vencimento_parcela_pedida': 'str'
        }

        self.attribute_map = {
            'id': 'id',
            'id_conta': 'idConta',
            'status_acordo': 'statusAcordo',
            'valor_acordo': 'valorAcordo',
            'data_acordo': 'dataAcordo',
            'quantidade_parcelas': 'quantidadeParcelas',
            'saldo_atual_final': 'saldoAtualFinal',
            'dias_em_atraso': 'diasEmAtraso',
            'status_conta': 'statusConta',
            'assessoria_atual': 'assessoriaAtual',
            'total_pagamentos': 'totalPagamentos',
            'data_vencimento_cobranca': 'dataVencimentoCobranca',
            'data_quebra_acordo': 'dataQuebraAcordo',
            'valor_parcela1': 'valorParcela1',
            'valor_parcela_n': 'valorParcelaN',
            'parcela_pedida': 'parcelaPedida',
            'vencimento_parcela_pedida': 'vencimentoParcelaPedida'
        }

        self._id = None
        self._id_conta = None
        self._status_acordo = None
        self._valor_acordo = None
        self._data_acordo = None
        self._quantidade_parcelas = None
        self._saldo_atual_final = None
        self._dias_em_atraso = None
        self._status_conta = None
        self._assessoria_atual = None
        self._total_pagamentos = None
        self._data_vencimento_cobranca = None
        self._data_quebra_acordo = None
        self._valor_parcela1 = None
        self._valor_parcela_n = None
        self._parcela_pedida = None
        self._vencimento_parcela_pedida = None

    @property
    def id(self):
        """
        Gets the id of this AcordoDetalheResponse.
        {{{acordo_response_id_value}}}

        :return: The id of this AcordoDetalheResponse.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this AcordoDetalheResponse.
        {{{acordo_response_id_value}}}

        :param id: The id of this AcordoDetalheResponse.
        :type: int
        """
        self._id = id

    @property
    def id_conta(self):
        """
        Gets the id_conta of this AcordoDetalheResponse.
        {{{acordo_response_id_conta_value}}}

        :return: The id_conta of this AcordoDetalheResponse.
        :rtype: int
        """
        return self._id_conta

    @id_conta.setter
    def id_conta(self, id_conta):
        """
        Sets the id_conta of this AcordoDetalheResponse.
        {{{acordo_response_id_conta_value}}}

        :param id_conta: The id_conta of this AcordoDetalheResponse.
        :type: int
        """
        self._id_conta = id_conta

    @property
    def status_acordo(self):
        """
        Gets the status_acordo of this AcordoDetalheResponse.
        {{{acordo_response_status_acordo_value}}}

        :return: The status_acordo of this AcordoDetalheResponse.
        :rtype: int
        """
        return self._status_acordo

    @status_acordo.setter
    def status_acordo(self, status_acordo):
        """
        Sets the status_acordo of this AcordoDetalheResponse.
        {{{acordo_response_status_acordo_value}}}

        :param status_acordo: The status_acordo of this AcordoDetalheResponse.
        :type: int
        """
        self._status_acordo = status_acordo

    @property
    def valor_acordo(self):
        """
        Gets the valor_acordo of this AcordoDetalheResponse.
        {{{acordo_response_valor_acordo_value}}}

        :return: The valor_acordo of this AcordoDetalheResponse.
        :rtype: float
        """
        return self._valor_acordo

    @valor_acordo.setter
    def valor_acordo(self, valor_acordo):
        """
        Sets the valor_acordo of this AcordoDetalheResponse.
        {{{acordo_response_valor_acordo_value}}}

        :param valor_acordo: The valor_acordo of this AcordoDetalheResponse.
        :type: float
        """
        self._valor_acordo = valor_acordo

    @property
    def data_acordo(self):
        """
        Gets the data_acordo of this AcordoDetalheResponse.
        {{{acordo_response_data_acordo_value}}}

        :return: The data_acordo of this AcordoDetalheResponse.
        :rtype: str
        """
        return self._data_acordo

    @data_acordo.setter
    def data_acordo(self, data_acordo):
        """
        Sets the data_acordo of this AcordoDetalheResponse.
        {{{acordo_response_data_acordo_value}}}

        :param data_acordo: The data_acordo of this AcordoDetalheResponse.
        :type: str
        """
        self._data_acordo = data_acordo

    @property
    def quantidade_parcelas(self):
        """
        Gets the quantidade_parcelas of this AcordoDetalheResponse.
        {{{acordo_response_quantidade_parcelas_value}}}

        :return: The quantidade_parcelas of this AcordoDetalheResponse.
        :rtype: int
        """
        return self._quantidade_parcelas

    @quantidade_parcelas.setter
    def quantidade_parcelas(self, quantidade_parcelas):
        """
        Sets the quantidade_parcelas of this AcordoDetalheResponse.
        {{{acordo_response_quantidade_parcelas_value}}}

        :param quantidade_parcelas: The quantidade_parcelas of this AcordoDetalheResponse.
        :type: int
        """
        self._quantidade_parcelas = quantidade_parcelas

    @property
    def saldo_atual_final(self):
        """
        Gets the saldo_atual_final of this AcordoDetalheResponse.
        {{{acordo_response_saldo_atual_final_value}}}

        :return: The saldo_atual_final of this AcordoDetalheResponse.
        :rtype: float
        """
        return self._saldo_atual_final

    @saldo_atual_final.setter
    def saldo_atual_final(self, saldo_atual_final):
        """
        Sets the saldo_atual_final of this AcordoDetalheResponse.
        {{{acordo_response_saldo_atual_final_value}}}

        :param saldo_atual_final: The saldo_atual_final of this AcordoDetalheResponse.
        :type: float
        """
        self._saldo_atual_final = saldo_atual_final

    @property
    def dias_em_atraso(self):
        """
        Gets the dias_em_atraso of this AcordoDetalheResponse.
        {{{acordo_response_dias_em_atraso_value}}}

        :return: The dias_em_atraso of this AcordoDetalheResponse.
        :rtype: int
        """
        return self._dias_em_atraso

    @dias_em_atraso.setter
    def dias_em_atraso(self, dias_em_atraso):
        """
        Sets the dias_em_atraso of this AcordoDetalheResponse.
        {{{acordo_response_dias_em_atraso_value}}}

        :param dias_em_atraso: The dias_em_atraso of this AcordoDetalheResponse.
        :type: int
        """
        self._dias_em_atraso = dias_em_atraso

    @property
    def status_conta(self):
        """
        Gets the status_conta of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_status_conta_value}}}

        :return: The status_conta of this AcordoDetalheResponse.
        :rtype: int
        """
        return self._status_conta

    @status_conta.setter
    def status_conta(self, status_conta):
        """
        Sets the status_conta of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_status_conta_value}}}

        :param status_conta: The status_conta of this AcordoDetalheResponse.
        :type: int
        """
        self._status_conta = status_conta

    @property
    def assessoria_atual(self):
        """
        Gets the assessoria_atual of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_assessoria_atual_value}}}

        :return: The assessoria_atual of this AcordoDetalheResponse.
        :rtype: str
        """
        return self._assessoria_atual

    @assessoria_atual.setter
    def assessoria_atual(self, assessoria_atual):
        """
        Sets the assessoria_atual of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_assessoria_atual_value}}}

        :param assessoria_atual: The assessoria_atual of this AcordoDetalheResponse.
        :type: str
        """
        self._assessoria_atual = assessoria_atual

    @property
    def total_pagamentos(self):
        """
        Gets the total_pagamentos of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_total_pagamentos_value}}}

        :return: The total_pagamentos of this AcordoDetalheResponse.
        :rtype: float
        """
        return self._total_pagamentos

    @total_pagamentos.setter
    def total_pagamentos(self, total_pagamentos):
        """
        Sets the total_pagamentos of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_total_pagamentos_value}}}

        :param total_pagamentos: The total_pagamentos of this AcordoDetalheResponse.
        :type: float
        """
        self._total_pagamentos = total_pagamentos

    @property
    def data_vencimento_cobranca(self):
        """
        Gets the data_vencimento_cobranca of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_data_vencimento_cobranca_value}}}

        :return: The data_vencimento_cobranca of this AcordoDetalheResponse.
        :rtype: str
        """
        return self._data_vencimento_cobranca

    @data_vencimento_cobranca.setter
    def data_vencimento_cobranca(self, data_vencimento_cobranca):
        """
        Sets the data_vencimento_cobranca of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_data_vencimento_cobranca_value}}}

        :param data_vencimento_cobranca: The data_vencimento_cobranca of this AcordoDetalheResponse.
        :type: str
        """
        self._data_vencimento_cobranca = data_vencimento_cobranca

    @property
    def data_quebra_acordo(self):
        """
        Gets the data_quebra_acordo of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_data_quebra_acordo_value}}}

        :return: The data_quebra_acordo of this AcordoDetalheResponse.
        :rtype: str
        """
        return self._data_quebra_acordo

    @data_quebra_acordo.setter
    def data_quebra_acordo(self, data_quebra_acordo):
        """
        Sets the data_quebra_acordo of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_data_quebra_acordo_value}}}

        :param data_quebra_acordo: The data_quebra_acordo of this AcordoDetalheResponse.
        :type: str
        """
        self._data_quebra_acordo = data_quebra_acordo

    @property
    def valor_parcela1(self):
        """
        Gets the valor_parcela1 of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_valor_parcela1_value}}}

        :return: The valor_parcela1 of this AcordoDetalheResponse.
        :rtype: float
        """
        return self._valor_parcela1

    @valor_parcela1.setter
    def valor_parcela1(self, valor_parcela1):
        """
        Sets the valor_parcela1 of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_valor_parcela1_value}}}

        :param valor_parcela1: The valor_parcela1 of this AcordoDetalheResponse.
        :type: float
        """
        self._valor_parcela1 = valor_parcela1

    @property
    def valor_parcela_n(self):
        """
        Gets the valor_parcela_n of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_valor_parcela_n_value}}}

        :return: The valor_parcela_n of this AcordoDetalheResponse.
        :rtype: float
        """
        return self._valor_parcela_n

    @valor_parcela_n.setter
    def valor_parcela_n(self, valor_parcela_n):
        """
        Sets the valor_parcela_n of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_valor_parcela_n_value}}}

        :param valor_parcela_n: The valor_parcela_n of this AcordoDetalheResponse.
        :type: float
        """
        self._valor_parcela_n = valor_parcela_n

    @property
    def parcela_pedida(self):
        """
        Gets the parcela_pedida of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_parcela_pedida_value}}}

        :return: The parcela_pedida of this AcordoDetalheResponse.
        :rtype: int
        """
        return self._parcela_pedida

    @parcela_pedida.setter
    def parcela_pedida(self, parcela_pedida):
        """
        Sets the parcela_pedida of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_parcela_pedida_value}}}

        :param parcela_pedida: The parcela_pedida of this AcordoDetalheResponse.
        :type: int
        """
        self._parcela_pedida = parcela_pedida

    @property
    def vencimento_parcela_pedida(self):
        """
        Gets the vencimento_parcela_pedida of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_vencimento_parcela_pedida_value}}}

        :return: The vencimento_parcela_pedida of this AcordoDetalheResponse.
        :rtype: str
        """
        return self._vencimento_parcela_pedida

    @vencimento_parcela_pedida.setter
    def vencimento_parcela_pedida(self, vencimento_parcela_pedida):
        """
        Sets the vencimento_parcela_pedida of this AcordoDetalheResponse.
        {{{acordo_detalhe_response_vencimento_parcela_pedida_value}}}

        :param vencimento_parcela_pedida: The vencimento_parcela_pedida of this AcordoDetalheResponse.
        :type: str
        """
        self._vencimento_parcela_pedida = vencimento_parcela_pedida

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

