# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class AdesaoPagamentoSabadoResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        AdesaoPagamentoSabadoResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'data_cadastro': 'str',
            'data_vencimento': 'str',
            'id': 'int',
            'id_conta': 'int'
        }

        self.attribute_map = {
            'data_cadastro': 'dataCadastro',
            'data_vencimento': 'dataVencimento',
            'id': 'id',
            'id_conta': 'idConta'
        }

        self._data_cadastro = None
        self._data_vencimento = None
        self._id = None
        self._id_conta = None

    @property
    def data_cadastro(self):
        """
        Gets the data_cadastro of this AdesaoPagamentoSabadoResponse.
        {{{adesao_pagamento_sabado_resposta_data_cadastro_descricao}}}

        :return: The data_cadastro of this AdesaoPagamentoSabadoResponse.
        :rtype: str
        """
        return self._data_cadastro

    @data_cadastro.setter
    def data_cadastro(self, data_cadastro):
        """
        Sets the data_cadastro of this AdesaoPagamentoSabadoResponse.
        {{{adesao_pagamento_sabado_resposta_data_cadastro_descricao}}}

        :param data_cadastro: The data_cadastro of this AdesaoPagamentoSabadoResponse.
        :type: str
        """
        self._data_cadastro = data_cadastro

    @property
    def data_vencimento(self):
        """
        Gets the data_vencimento of this AdesaoPagamentoSabadoResponse.
        {{{adesao_pagamento_sabado_resposta_data_vencimento_descricao}}}

        :return: The data_vencimento of this AdesaoPagamentoSabadoResponse.
        :rtype: str
        """
        return self._data_vencimento

    @data_vencimento.setter
    def data_vencimento(self, data_vencimento):
        """
        Sets the data_vencimento of this AdesaoPagamentoSabadoResponse.
        {{{adesao_pagamento_sabado_resposta_data_vencimento_descricao}}}

        :param data_vencimento: The data_vencimento of this AdesaoPagamentoSabadoResponse.
        :type: str
        """
        self._data_vencimento = data_vencimento

    @property
    def id(self):
        """
        Gets the id of this AdesaoPagamentoSabadoResponse.
        {{{adesao_pagamento_sabado_resposta_id_descricao}}}

        :return: The id of this AdesaoPagamentoSabadoResponse.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this AdesaoPagamentoSabadoResponse.
        {{{adesao_pagamento_sabado_resposta_id_descricao}}}

        :param id: The id of this AdesaoPagamentoSabadoResponse.
        :type: int
        """
        self._id = id

    @property
    def id_conta(self):
        """
        Gets the id_conta of this AdesaoPagamentoSabadoResponse.
        {{{adesao_pagamento_sabado_resposta_id_conta_descricao}}}

        :return: The id_conta of this AdesaoPagamentoSabadoResponse.
        :rtype: int
        """
        return self._id_conta

    @id_conta.setter
    def id_conta(self, id_conta):
        """
        Sets the id_conta of this AdesaoPagamentoSabadoResponse.
        {{{adesao_pagamento_sabado_resposta_id_conta_descricao}}}

        :param id_conta: The id_conta of this AdesaoPagamentoSabadoResponse.
        :type: int
        """
        self._id_conta = id_conta

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

