# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class AtendimentoClienteResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        AtendimentoClienteResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id_atendimento': 'int',
            'id_conta': 'int',
            'id_tipo_atendimento': 'int',
            'descricao_tipo_atendimento': 'str',
            'conteudo_atendimento': 'str',
            'detalhes_atendimento': 'str',
            'nome_atendente': 'str',
            'nome_sistema': 'str',
            'data_hora_inicio_atendimento': 'str',
            'data_hora_fim_atendimento': 'str',
            'data_atendimento': 'str',
            'data_agendamento': 'str',
            'data_processamento': 'str',
            'flag_processamento': 'int'
        }

        self.attribute_map = {
            'id_atendimento': 'idAtendimento',
            'id_conta': 'idConta',
            'id_tipo_atendimento': 'idTipoAtendimento',
            'descricao_tipo_atendimento': 'descricaoTipoAtendimento',
            'conteudo_atendimento': 'conteudoAtendimento',
            'detalhes_atendimento': 'detalhesAtendimento',
            'nome_atendente': 'nomeAtendente',
            'nome_sistema': 'nomeSistema',
            'data_hora_inicio_atendimento': 'dataHoraInicioAtendimento',
            'data_hora_fim_atendimento': 'dataHoraFimAtendimento',
            'data_atendimento': 'dataAtendimento',
            'data_agendamento': 'dataAgendamento',
            'data_processamento': 'dataProcessamento',
            'flag_processamento': 'flagProcessamento'
        }

        self._id_atendimento = None
        self._id_conta = None
        self._id_tipo_atendimento = None
        self._descricao_tipo_atendimento = None
        self._conteudo_atendimento = None
        self._detalhes_atendimento = None
        self._nome_atendente = None
        self._nome_sistema = None
        self._data_hora_inicio_atendimento = None
        self._data_hora_fim_atendimento = None
        self._data_atendimento = None
        self._data_agendamento = None
        self._data_processamento = None
        self._flag_processamento = None

    @property
    def id_atendimento(self):
        """
        Gets the id_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_id_atendimento_value}}}

        :return: The id_atendimento of this AtendimentoClienteResponse.
        :rtype: int
        """
        return self._id_atendimento

    @id_atendimento.setter
    def id_atendimento(self, id_atendimento):
        """
        Sets the id_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_id_atendimento_value}}}

        :param id_atendimento: The id_atendimento of this AtendimentoClienteResponse.
        :type: int
        """
        self._id_atendimento = id_atendimento

    @property
    def id_conta(self):
        """
        Gets the id_conta of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_id_conta_value}}}

        :return: The id_conta of this AtendimentoClienteResponse.
        :rtype: int
        """
        return self._id_conta

    @id_conta.setter
    def id_conta(self, id_conta):
        """
        Sets the id_conta of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_id_conta_value}}}

        :param id_conta: The id_conta of this AtendimentoClienteResponse.
        :type: int
        """
        self._id_conta = id_conta

    @property
    def id_tipo_atendimento(self):
        """
        Gets the id_tipo_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_id_tipo_atendimento_value}}}

        :return: The id_tipo_atendimento of this AtendimentoClienteResponse.
        :rtype: int
        """
        return self._id_tipo_atendimento

    @id_tipo_atendimento.setter
    def id_tipo_atendimento(self, id_tipo_atendimento):
        """
        Sets the id_tipo_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_id_tipo_atendimento_value}}}

        :param id_tipo_atendimento: The id_tipo_atendimento of this AtendimentoClienteResponse.
        :type: int
        """
        self._id_tipo_atendimento = id_tipo_atendimento

    @property
    def descricao_tipo_atendimento(self):
        """
        Gets the descricao_tipo_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_descricao_tipo_atendimento_value}}}

        :return: The descricao_tipo_atendimento of this AtendimentoClienteResponse.
        :rtype: str
        """
        return self._descricao_tipo_atendimento

    @descricao_tipo_atendimento.setter
    def descricao_tipo_atendimento(self, descricao_tipo_atendimento):
        """
        Sets the descricao_tipo_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_descricao_tipo_atendimento_value}}}

        :param descricao_tipo_atendimento: The descricao_tipo_atendimento of this AtendimentoClienteResponse.
        :type: str
        """
        self._descricao_tipo_atendimento = descricao_tipo_atendimento

    @property
    def conteudo_atendimento(self):
        """
        Gets the conteudo_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_conteudo_atendimento_value}}}

        :return: The conteudo_atendimento of this AtendimentoClienteResponse.
        :rtype: str
        """
        return self._conteudo_atendimento

    @conteudo_atendimento.setter
    def conteudo_atendimento(self, conteudo_atendimento):
        """
        Sets the conteudo_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_conteudo_atendimento_value}}}

        :param conteudo_atendimento: The conteudo_atendimento of this AtendimentoClienteResponse.
        :type: str
        """
        self._conteudo_atendimento = conteudo_atendimento

    @property
    def detalhes_atendimento(self):
        """
        Gets the detalhes_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_detalhes_atendimento_value}}}

        :return: The detalhes_atendimento of this AtendimentoClienteResponse.
        :rtype: str
        """
        return self._detalhes_atendimento

    @detalhes_atendimento.setter
    def detalhes_atendimento(self, detalhes_atendimento):
        """
        Sets the detalhes_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_detalhes_atendimento_value}}}

        :param detalhes_atendimento: The detalhes_atendimento of this AtendimentoClienteResponse.
        :type: str
        """
        self._detalhes_atendimento = detalhes_atendimento

    @property
    def nome_atendente(self):
        """
        Gets the nome_atendente of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_nome_atendente_value}}}

        :return: The nome_atendente of this AtendimentoClienteResponse.
        :rtype: str
        """
        return self._nome_atendente

    @nome_atendente.setter
    def nome_atendente(self, nome_atendente):
        """
        Sets the nome_atendente of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_nome_atendente_value}}}

        :param nome_atendente: The nome_atendente of this AtendimentoClienteResponse.
        :type: str
        """
        self._nome_atendente = nome_atendente

    @property
    def nome_sistema(self):
        """
        Gets the nome_sistema of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_nome_sistema_value}}}

        :return: The nome_sistema of this AtendimentoClienteResponse.
        :rtype: str
        """
        return self._nome_sistema

    @nome_sistema.setter
    def nome_sistema(self, nome_sistema):
        """
        Sets the nome_sistema of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_nome_sistema_value}}}

        :param nome_sistema: The nome_sistema of this AtendimentoClienteResponse.
        :type: str
        """
        self._nome_sistema = nome_sistema

    @property
    def data_hora_inicio_atendimento(self):
        """
        Gets the data_hora_inicio_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_data_hora_inicio_atendimento_value}}}

        :return: The data_hora_inicio_atendimento of this AtendimentoClienteResponse.
        :rtype: str
        """
        return self._data_hora_inicio_atendimento

    @data_hora_inicio_atendimento.setter
    def data_hora_inicio_atendimento(self, data_hora_inicio_atendimento):
        """
        Sets the data_hora_inicio_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_data_hora_inicio_atendimento_value}}}

        :param data_hora_inicio_atendimento: The data_hora_inicio_atendimento of this AtendimentoClienteResponse.
        :type: str
        """
        self._data_hora_inicio_atendimento = data_hora_inicio_atendimento

    @property
    def data_hora_fim_atendimento(self):
        """
        Gets the data_hora_fim_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_data_hora_fim_atendimento_value}}}

        :return: The data_hora_fim_atendimento of this AtendimentoClienteResponse.
        :rtype: str
        """
        return self._data_hora_fim_atendimento

    @data_hora_fim_atendimento.setter
    def data_hora_fim_atendimento(self, data_hora_fim_atendimento):
        """
        Sets the data_hora_fim_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_data_hora_fim_atendimento_value}}}

        :param data_hora_fim_atendimento: The data_hora_fim_atendimento of this AtendimentoClienteResponse.
        :type: str
        """
        self._data_hora_fim_atendimento = data_hora_fim_atendimento

    @property
    def data_atendimento(self):
        """
        Gets the data_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_data_atendimento_value}}}

        :return: The data_atendimento of this AtendimentoClienteResponse.
        :rtype: str
        """
        return self._data_atendimento

    @data_atendimento.setter
    def data_atendimento(self, data_atendimento):
        """
        Sets the data_atendimento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_data_atendimento_value}}}

        :param data_atendimento: The data_atendimento of this AtendimentoClienteResponse.
        :type: str
        """
        self._data_atendimento = data_atendimento

    @property
    def data_agendamento(self):
        """
        Gets the data_agendamento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_data_agendamento_value}}}

        :return: The data_agendamento of this AtendimentoClienteResponse.
        :rtype: str
        """
        return self._data_agendamento

    @data_agendamento.setter
    def data_agendamento(self, data_agendamento):
        """
        Sets the data_agendamento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_data_agendamento_value}}}

        :param data_agendamento: The data_agendamento of this AtendimentoClienteResponse.
        :type: str
        """
        self._data_agendamento = data_agendamento

    @property
    def data_processamento(self):
        """
        Gets the data_processamento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_data_processamento_value}}}

        :return: The data_processamento of this AtendimentoClienteResponse.
        :rtype: str
        """
        return self._data_processamento

    @data_processamento.setter
    def data_processamento(self, data_processamento):
        """
        Sets the data_processamento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_data_processamento_value}}}

        :param data_processamento: The data_processamento of this AtendimentoClienteResponse.
        :type: str
        """
        self._data_processamento = data_processamento

    @property
    def flag_processamento(self):
        """
        Gets the flag_processamento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_flag_processamento_value}}}

        :return: The flag_processamento of this AtendimentoClienteResponse.
        :rtype: int
        """
        return self._flag_processamento

    @flag_processamento.setter
    def flag_processamento(self, flag_processamento):
        """
        Sets the flag_processamento of this AtendimentoClienteResponse.
        {{{atendimento_cliente_response_flag_processamento_value}}}

        :param flag_processamento: The flag_processamento of this AtendimentoClienteResponse.
        :type: int
        """
        self._flag_processamento = flag_processamento

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

