# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class ControleTentativaCadastroResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        ControleTentativaCadastroResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'cpf': 'str',
            'login': 'str',
            'tentativas': 'int'
        }

        self.attribute_map = {
            'cpf': 'cpf',
            'login': 'login',
            'tentativas': 'tentativas'
        }

        self._cpf = None
        self._login = None
        self._tentativas = None

    @property
    def cpf(self):
        """
        Gets the cpf of this ControleTentativaCadastroResponse.
        {{{controle_tentativa_cadastro_resposta_cpf_descricao}}}

        :return: The cpf of this ControleTentativaCadastroResponse.
        :rtype: str
        """
        return self._cpf

    @cpf.setter
    def cpf(self, cpf):
        """
        Sets the cpf of this ControleTentativaCadastroResponse.
        {{{controle_tentativa_cadastro_resposta_cpf_descricao}}}

        :param cpf: The cpf of this ControleTentativaCadastroResponse.
        :type: str
        """
        self._cpf = cpf

    @property
    def login(self):
        """
        Gets the login of this ControleTentativaCadastroResponse.
        {{{controle_tentativa_cadastro_resposta_login_descricao}}}

        :return: The login of this ControleTentativaCadastroResponse.
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login):
        """
        Sets the login of this ControleTentativaCadastroResponse.
        {{{controle_tentativa_cadastro_resposta_login_descricao}}}

        :param login: The login of this ControleTentativaCadastroResponse.
        :type: str
        """
        self._login = login

    @property
    def tentativas(self):
        """
        Gets the tentativas of this ControleTentativaCadastroResponse.
        {{{controle_tentativa_cadastro_resposta_tentativas_descricao}}}

        :return: The tentativas of this ControleTentativaCadastroResponse.
        :rtype: int
        """
        return self._tentativas

    @tentativas.setter
    def tentativas(self, tentativas):
        """
        Sets the tentativas of this ControleTentativaCadastroResponse.
        {{{controle_tentativa_cadastro_resposta_tentativas_descricao}}}

        :param tentativas: The tentativas of this ControleTentativaCadastroResponse.
        :type: int
        """
        self._tentativas = tentativas

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

