# coding: utf-8

"""
Copyright 2016 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class FaturaConsignadaDetalheResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        FaturaConsignadaDetalheResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'id_conta': 'int',
            'limite_global': 'float',
            'flag_emite_fatura': 'int',
            'limite_compra': 'float',
            'data_vencimento_fatura': 'str',
            'limite_parcelado': 'float',
            'limite_parcelas': 'float',
            'valor_total_fatura': 'float',
            'valor_fatura_anterior': 'float',
            'valor_pagamento_minimo': 'float',
            'valor_pagamento_consignado': 'float',
            'limite_saque_global': 'float',
            'valor_pagamento_complementar': 'float',
            'limite_saque_periodo': 'float',
            'total_compras_nacionais': 'float',
            'limite_consignado': 'float',
            'total_compras_internacionas': 'float',
            'limite_internacional_compra': 'float',
            'total_saques_nacionais': 'float',
            'limite_internacional_parcelado': 'float',
            'total_saques_internacionais': 'float',
            'limite_internacional_parcelas': 'float',
            'total_debitos_nacionais': 'float',
            'limite_internacional_saque_global': 'float',
            'total_debitos_recorrentes': 'float',
            'limite_internacional_saque_periodo': 'float',
            'total_debitos_internacionais': 'float',
            'saldo_disponivel_global': 'float',
            'total_debitos_diversos_nacionais': 'float',
            'saldo_disponivel_compra': 'float',
            'total_debitos_opcionais': 'float',
            'saldo_disponivel_parcelado': 'float',
            'total_pagamentos': 'float',
            'saldo_disponivel_parcelas': 'float',
            'total_creditos_nacionais': 'float',
            'total_ajustes': 'float',
            'total_tarifas': 'float',
            'total_multa': 'float',
            'saldo_disponivel_saque': 'float',
            'total_juros': 'float',
            'saldo_pontos_fidelidade': 'float',
            'taxa_rotativo': 'float',
            'saldo_disponivel_compra_internacional': 'float',
            'taxa_saque': 'float',
            'saldo_disponivel_saque_internacional': 'float',
            'taxa_maxima_proximo_periodo': 'float',
            'total_servicos': 'float'
        }

        self.attribute_map = {
            'id': 'id',
            'id_conta': 'idConta',
            'limite_global': 'limiteGlobal',
            'flag_emite_fatura': 'flagEmiteFatura',
            'limite_compra': 'limiteCompra',
            'data_vencimento_fatura': 'dataVencimentoFatura',
            'limite_parcelado': 'limiteParcelado',
            'limite_parcelas': 'limiteParcelas',
            'valor_total_fatura': 'valorTotalFatura',
            'valor_fatura_anterior': 'valorFaturaAnterior',
            'valor_pagamento_minimo': 'valorPagamentoMinimo',
            'valor_pagamento_consignado': 'valorPagamentoConsignado',
            'limite_saque_global': 'limiteSaqueGlobal',
            'valor_pagamento_complementar': 'valorPagamentoComplementar',
            'limite_saque_periodo': 'limiteSaquePeriodo',
            'total_compras_nacionais': 'totalComprasNacionais',
            'limite_consignado': 'limiteConsignado',
            'total_compras_internacionas': 'totalComprasInternacionas',
            'limite_internacional_compra': 'limiteInternacionalCompra',
            'total_saques_nacionais': 'totalSaquesNacionais',
            'limite_internacional_parcelado': 'limiteInternacionalParcelado',
            'total_saques_internacionais': 'totalSaquesInternacionais',
            'limite_internacional_parcelas': 'limiteInternacionalParcelas',
            'total_debitos_nacionais': 'totalDebitosNacionais',
            'limite_internacional_saque_global': 'limiteInternacionalSaqueGlobal',
            'total_debitos_recorrentes': 'totalDebitosRecorrentes',
            'limite_internacional_saque_periodo': 'limiteInternacionalSaquePeriodo',
            'total_debitos_internacionais': 'totalDebitosInternacionais',
            'saldo_disponivel_global': 'saldoDisponivelGlobal',
            'total_debitos_diversos_nacionais': 'totalDebitosDiversosNacionais',
            'saldo_disponivel_compra': 'saldoDisponivelCompra',
            'total_debitos_opcionais': 'totalDebitosOpcionais',
            'saldo_disponivel_parcelado': 'saldoDisponivelParcelado',
            'total_pagamentos': 'totalPagamentos',
            'saldo_disponivel_parcelas': 'saldoDisponivelParcelas',
            'total_creditos_nacionais': 'totalCreditosNacionais',
            'total_ajustes': 'totalAjustes',
            'total_tarifas': 'totalTarifas',
            'total_multa': 'totalMulta',
            'saldo_disponivel_saque': 'saldoDisponivelSaque',
            'total_juros': 'totalJuros',
            'saldo_pontos_fidelidade': 'saldoPontosFidelidade',
            'taxa_rotativo': 'taxaRotativo',
            'saldo_disponivel_compra_internacional': 'saldoDisponivelCompraInternacional',
            'taxa_saque': 'taxaSaque',
            'saldo_disponivel_saque_internacional': 'saldoDisponivelSaqueInternacional',
            'taxa_maxima_proximo_periodo': 'taxaMaximaProximoPeriodo',
            'total_servicos': 'totalServicos'
        }

        self._id = None
        self._id_conta = None
        self._limite_global = None
        self._flag_emite_fatura = None
        self._limite_compra = None
        self._data_vencimento_fatura = None
        self._limite_parcelado = None
        self._limite_parcelas = None
        self._valor_total_fatura = None
        self._valor_fatura_anterior = None
        self._valor_pagamento_minimo = None
        self._valor_pagamento_consignado = None
        self._limite_saque_global = None
        self._valor_pagamento_complementar = None
        self._limite_saque_periodo = None
        self._total_compras_nacionais = None
        self._limite_consignado = None
        self._total_compras_internacionas = None
        self._limite_internacional_compra = None
        self._total_saques_nacionais = None
        self._limite_internacional_parcelado = None
        self._total_saques_internacionais = None
        self._limite_internacional_parcelas = None
        self._total_debitos_nacionais = None
        self._limite_internacional_saque_global = None
        self._total_debitos_recorrentes = None
        self._limite_internacional_saque_periodo = None
        self._total_debitos_internacionais = None
        self._saldo_disponivel_global = None
        self._total_debitos_diversos_nacionais = None
        self._saldo_disponivel_compra = None
        self._total_debitos_opcionais = None
        self._saldo_disponivel_parcelado = None
        self._total_pagamentos = None
        self._saldo_disponivel_parcelas = None
        self._total_creditos_nacionais = None
        self._total_ajustes = None
        self._total_tarifas = None
        self._total_multa = None
        self._saldo_disponivel_saque = None
        self._total_juros = None
        self._saldo_pontos_fidelidade = None
        self._taxa_rotativo = None
        self._saldo_disponivel_compra_internacional = None
        self._taxa_saque = None
        self._saldo_disponivel_saque_internacional = None
        self._taxa_maxima_proximo_periodo = None
        self._total_servicos = None

    @property
    def id(self):
        """
        Gets the id of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_id_value}}}

        :return: The id of this FaturaConsignadaDetalheResponse.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_id_value}}}

        :param id: The id of this FaturaConsignadaDetalheResponse.
        :type: int
        """
        self._id = id

    @property
    def id_conta(self):
        """
        Gets the id_conta of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_id_conta_value}}}

        :return: The id_conta of this FaturaConsignadaDetalheResponse.
        :rtype: int
        """
        return self._id_conta

    @id_conta.setter
    def id_conta(self, id_conta):
        """
        Sets the id_conta of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_id_conta_value}}}

        :param id_conta: The id_conta of this FaturaConsignadaDetalheResponse.
        :type: int
        """
        self._id_conta = id_conta

    @property
    def limite_global(self):
        """
        Gets the limite_global of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_global_value}}}

        :return: The limite_global of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_global

    @limite_global.setter
    def limite_global(self, limite_global):
        """
        Sets the limite_global of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_global_value}}}

        :param limite_global: The limite_global of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_global = limite_global

    @property
    def flag_emite_fatura(self):
        """
        Gets the flag_emite_fatura of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_flag_emite_fatura_value}}}

        :return: The flag_emite_fatura of this FaturaConsignadaDetalheResponse.
        :rtype: int
        """
        return self._flag_emite_fatura

    @flag_emite_fatura.setter
    def flag_emite_fatura(self, flag_emite_fatura):
        """
        Sets the flag_emite_fatura of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_flag_emite_fatura_value}}}

        :param flag_emite_fatura: The flag_emite_fatura of this FaturaConsignadaDetalheResponse.
        :type: int
        """
        self._flag_emite_fatura = flag_emite_fatura

    @property
    def limite_compra(self):
        """
        Gets the limite_compra of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_compra_value}}}

        :return: The limite_compra of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_compra

    @limite_compra.setter
    def limite_compra(self, limite_compra):
        """
        Sets the limite_compra of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_compra_value}}}

        :param limite_compra: The limite_compra of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_compra = limite_compra

    @property
    def data_vencimento_fatura(self):
        """
        Gets the data_vencimento_fatura of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_data_vencimento_fatura_value}}}

        :return: The data_vencimento_fatura of this FaturaConsignadaDetalheResponse.
        :rtype: str
        """
        return self._data_vencimento_fatura

    @data_vencimento_fatura.setter
    def data_vencimento_fatura(self, data_vencimento_fatura):
        """
        Sets the data_vencimento_fatura of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_data_vencimento_fatura_value}}}

        :param data_vencimento_fatura: The data_vencimento_fatura of this FaturaConsignadaDetalheResponse.
        :type: str
        """
        self._data_vencimento_fatura = data_vencimento_fatura

    @property
    def limite_parcelado(self):
        """
        Gets the limite_parcelado of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_parcelado_value}}}

        :return: The limite_parcelado of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_parcelado

    @limite_parcelado.setter
    def limite_parcelado(self, limite_parcelado):
        """
        Sets the limite_parcelado of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_parcelado_value}}}

        :param limite_parcelado: The limite_parcelado of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_parcelado = limite_parcelado

    @property
    def limite_parcelas(self):
        """
        Gets the limite_parcelas of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_parcelas_value}}}

        :return: The limite_parcelas of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_parcelas

    @limite_parcelas.setter
    def limite_parcelas(self, limite_parcelas):
        """
        Sets the limite_parcelas of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_parcelas_value}}}

        :param limite_parcelas: The limite_parcelas of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_parcelas = limite_parcelas

    @property
    def valor_total_fatura(self):
        """
        Gets the valor_total_fatura of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_valor_total_fatura_value}}}

        :return: The valor_total_fatura of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._valor_total_fatura

    @valor_total_fatura.setter
    def valor_total_fatura(self, valor_total_fatura):
        """
        Sets the valor_total_fatura of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_valor_total_fatura_value}}}

        :param valor_total_fatura: The valor_total_fatura of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._valor_total_fatura = valor_total_fatura

    @property
    def valor_fatura_anterior(self):
        """
        Gets the valor_fatura_anterior of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_valor_fatura_anterior_value}}}

        :return: The valor_fatura_anterior of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._valor_fatura_anterior

    @valor_fatura_anterior.setter
    def valor_fatura_anterior(self, valor_fatura_anterior):
        """
        Sets the valor_fatura_anterior of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_valor_fatura_anterior_value}}}

        :param valor_fatura_anterior: The valor_fatura_anterior of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._valor_fatura_anterior = valor_fatura_anterior

    @property
    def valor_pagamento_minimo(self):
        """
        Gets the valor_pagamento_minimo of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_valor_pagamento_minimo_value}}}

        :return: The valor_pagamento_minimo of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._valor_pagamento_minimo

    @valor_pagamento_minimo.setter
    def valor_pagamento_minimo(self, valor_pagamento_minimo):
        """
        Sets the valor_pagamento_minimo of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_valor_pagamento_minimo_value}}}

        :param valor_pagamento_minimo: The valor_pagamento_minimo of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._valor_pagamento_minimo = valor_pagamento_minimo

    @property
    def valor_pagamento_consignado(self):
        """
        Gets the valor_pagamento_consignado of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_valor_pagamento_consignado_value}}}

        :return: The valor_pagamento_consignado of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._valor_pagamento_consignado

    @valor_pagamento_consignado.setter
    def valor_pagamento_consignado(self, valor_pagamento_consignado):
        """
        Sets the valor_pagamento_consignado of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_valor_pagamento_consignado_value}}}

        :param valor_pagamento_consignado: The valor_pagamento_consignado of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._valor_pagamento_consignado = valor_pagamento_consignado

    @property
    def limite_saque_global(self):
        """
        Gets the limite_saque_global of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_saque_global_value}}}

        :return: The limite_saque_global of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_saque_global

    @limite_saque_global.setter
    def limite_saque_global(self, limite_saque_global):
        """
        Sets the limite_saque_global of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_saque_global_value}}}

        :param limite_saque_global: The limite_saque_global of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_saque_global = limite_saque_global

    @property
    def valor_pagamento_complementar(self):
        """
        Gets the valor_pagamento_complementar of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_valor_pagamento_complementar_value}}}

        :return: The valor_pagamento_complementar of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._valor_pagamento_complementar

    @valor_pagamento_complementar.setter
    def valor_pagamento_complementar(self, valor_pagamento_complementar):
        """
        Sets the valor_pagamento_complementar of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_valor_pagamento_complementar_value}}}

        :param valor_pagamento_complementar: The valor_pagamento_complementar of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._valor_pagamento_complementar = valor_pagamento_complementar

    @property
    def limite_saque_periodo(self):
        """
        Gets the limite_saque_periodo of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_saque_periodo_value}}}

        :return: The limite_saque_periodo of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_saque_periodo

    @limite_saque_periodo.setter
    def limite_saque_periodo(self, limite_saque_periodo):
        """
        Sets the limite_saque_periodo of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_saque_periodo_value}}}

        :param limite_saque_periodo: The limite_saque_periodo of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_saque_periodo = limite_saque_periodo

    @property
    def total_compras_nacionais(self):
        """
        Gets the total_compras_nacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_compras_nacionais_value}}}

        :return: The total_compras_nacionais of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_compras_nacionais

    @total_compras_nacionais.setter
    def total_compras_nacionais(self, total_compras_nacionais):
        """
        Sets the total_compras_nacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_compras_nacionais_value}}}

        :param total_compras_nacionais: The total_compras_nacionais of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_compras_nacionais = total_compras_nacionais

    @property
    def limite_consignado(self):
        """
        Gets the limite_consignado of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_consignado_value}}}

        :return: The limite_consignado of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_consignado

    @limite_consignado.setter
    def limite_consignado(self, limite_consignado):
        """
        Sets the limite_consignado of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_consignado_value}}}

        :param limite_consignado: The limite_consignado of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_consignado = limite_consignado

    @property
    def total_compras_internacionas(self):
        """
        Gets the total_compras_internacionas of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_compras_internacionas_value}}}

        :return: The total_compras_internacionas of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_compras_internacionas

    @total_compras_internacionas.setter
    def total_compras_internacionas(self, total_compras_internacionas):
        """
        Sets the total_compras_internacionas of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_compras_internacionas_value}}}

        :param total_compras_internacionas: The total_compras_internacionas of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_compras_internacionas = total_compras_internacionas

    @property
    def limite_internacional_compra(self):
        """
        Gets the limite_internacional_compra of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_internacional_compra_value}}}

        :return: The limite_internacional_compra of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_internacional_compra

    @limite_internacional_compra.setter
    def limite_internacional_compra(self, limite_internacional_compra):
        """
        Sets the limite_internacional_compra of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_internacional_compra_value}}}

        :param limite_internacional_compra: The limite_internacional_compra of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_internacional_compra = limite_internacional_compra

    @property
    def total_saques_nacionais(self):
        """
        Gets the total_saques_nacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_saques_nacionais_value}}}

        :return: The total_saques_nacionais of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_saques_nacionais

    @total_saques_nacionais.setter
    def total_saques_nacionais(self, total_saques_nacionais):
        """
        Sets the total_saques_nacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_saques_nacionais_value}}}

        :param total_saques_nacionais: The total_saques_nacionais of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_saques_nacionais = total_saques_nacionais

    @property
    def limite_internacional_parcelado(self):
        """
        Gets the limite_internacional_parcelado of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_internacional_parcelado_value}}}

        :return: The limite_internacional_parcelado of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_internacional_parcelado

    @limite_internacional_parcelado.setter
    def limite_internacional_parcelado(self, limite_internacional_parcelado):
        """
        Sets the limite_internacional_parcelado of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_internacional_parcelado_value}}}

        :param limite_internacional_parcelado: The limite_internacional_parcelado of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_internacional_parcelado = limite_internacional_parcelado

    @property
    def total_saques_internacionais(self):
        """
        Gets the total_saques_internacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_saques_internacionais_value}}}

        :return: The total_saques_internacionais of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_saques_internacionais

    @total_saques_internacionais.setter
    def total_saques_internacionais(self, total_saques_internacionais):
        """
        Sets the total_saques_internacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_saques_internacionais_value}}}

        :param total_saques_internacionais: The total_saques_internacionais of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_saques_internacionais = total_saques_internacionais

    @property
    def limite_internacional_parcelas(self):
        """
        Gets the limite_internacional_parcelas of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_internacional_parcelas_value}}}

        :return: The limite_internacional_parcelas of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_internacional_parcelas

    @limite_internacional_parcelas.setter
    def limite_internacional_parcelas(self, limite_internacional_parcelas):
        """
        Sets the limite_internacional_parcelas of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_internacional_parcelas_value}}}

        :param limite_internacional_parcelas: The limite_internacional_parcelas of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_internacional_parcelas = limite_internacional_parcelas

    @property
    def total_debitos_nacionais(self):
        """
        Gets the total_debitos_nacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_debitos_nacionais_value}}}

        :return: The total_debitos_nacionais of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_debitos_nacionais

    @total_debitos_nacionais.setter
    def total_debitos_nacionais(self, total_debitos_nacionais):
        """
        Sets the total_debitos_nacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_debitos_nacionais_value}}}

        :param total_debitos_nacionais: The total_debitos_nacionais of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_debitos_nacionais = total_debitos_nacionais

    @property
    def limite_internacional_saque_global(self):
        """
        Gets the limite_internacional_saque_global of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_internacional_saque_global_value}}}

        :return: The limite_internacional_saque_global of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_internacional_saque_global

    @limite_internacional_saque_global.setter
    def limite_internacional_saque_global(self, limite_internacional_saque_global):
        """
        Sets the limite_internacional_saque_global of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_internacional_saque_global_value}}}

        :param limite_internacional_saque_global: The limite_internacional_saque_global of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_internacional_saque_global = limite_internacional_saque_global

    @property
    def total_debitos_recorrentes(self):
        """
        Gets the total_debitos_recorrentes of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_debitos_recorrentes_value}}}

        :return: The total_debitos_recorrentes of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_debitos_recorrentes

    @total_debitos_recorrentes.setter
    def total_debitos_recorrentes(self, total_debitos_recorrentes):
        """
        Sets the total_debitos_recorrentes of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_debitos_recorrentes_value}}}

        :param total_debitos_recorrentes: The total_debitos_recorrentes of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_debitos_recorrentes = total_debitos_recorrentes

    @property
    def limite_internacional_saque_periodo(self):
        """
        Gets the limite_internacional_saque_periodo of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_internacional_saque_periodo_value}}}

        :return: The limite_internacional_saque_periodo of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._limite_internacional_saque_periodo

    @limite_internacional_saque_periodo.setter
    def limite_internacional_saque_periodo(self, limite_internacional_saque_periodo):
        """
        Sets the limite_internacional_saque_periodo of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_limite_internacional_saque_periodo_value}}}

        :param limite_internacional_saque_periodo: The limite_internacional_saque_periodo of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._limite_internacional_saque_periodo = limite_internacional_saque_periodo

    @property
    def total_debitos_internacionais(self):
        """
        Gets the total_debitos_internacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_debitos_internacionais_value}}}

        :return: The total_debitos_internacionais of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_debitos_internacionais

    @total_debitos_internacionais.setter
    def total_debitos_internacionais(self, total_debitos_internacionais):
        """
        Sets the total_debitos_internacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_debitos_internacionais_value}}}

        :param total_debitos_internacionais: The total_debitos_internacionais of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_debitos_internacionais = total_debitos_internacionais

    @property
    def saldo_disponivel_global(self):
        """
        Gets the saldo_disponivel_global of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_global_value}}}

        :return: The saldo_disponivel_global of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._saldo_disponivel_global

    @saldo_disponivel_global.setter
    def saldo_disponivel_global(self, saldo_disponivel_global):
        """
        Sets the saldo_disponivel_global of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_global_value}}}

        :param saldo_disponivel_global: The saldo_disponivel_global of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._saldo_disponivel_global = saldo_disponivel_global

    @property
    def total_debitos_diversos_nacionais(self):
        """
        Gets the total_debitos_diversos_nacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_debitos_diversos_nacionais_value}}}

        :return: The total_debitos_diversos_nacionais of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_debitos_diversos_nacionais

    @total_debitos_diversos_nacionais.setter
    def total_debitos_diversos_nacionais(self, total_debitos_diversos_nacionais):
        """
        Sets the total_debitos_diversos_nacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_debitos_diversos_nacionais_value}}}

        :param total_debitos_diversos_nacionais: The total_debitos_diversos_nacionais of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_debitos_diversos_nacionais = total_debitos_diversos_nacionais

    @property
    def saldo_disponivel_compra(self):
        """
        Gets the saldo_disponivel_compra of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_compra_value}}}

        :return: The saldo_disponivel_compra of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._saldo_disponivel_compra

    @saldo_disponivel_compra.setter
    def saldo_disponivel_compra(self, saldo_disponivel_compra):
        """
        Sets the saldo_disponivel_compra of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_compra_value}}}

        :param saldo_disponivel_compra: The saldo_disponivel_compra of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._saldo_disponivel_compra = saldo_disponivel_compra

    @property
    def total_debitos_opcionais(self):
        """
        Gets the total_debitos_opcionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_debitos_opcionais_value}}}

        :return: The total_debitos_opcionais of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_debitos_opcionais

    @total_debitos_opcionais.setter
    def total_debitos_opcionais(self, total_debitos_opcionais):
        """
        Sets the total_debitos_opcionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_debitos_opcionais_value}}}

        :param total_debitos_opcionais: The total_debitos_opcionais of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_debitos_opcionais = total_debitos_opcionais

    @property
    def saldo_disponivel_parcelado(self):
        """
        Gets the saldo_disponivel_parcelado of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_parcelado_value}}}

        :return: The saldo_disponivel_parcelado of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._saldo_disponivel_parcelado

    @saldo_disponivel_parcelado.setter
    def saldo_disponivel_parcelado(self, saldo_disponivel_parcelado):
        """
        Sets the saldo_disponivel_parcelado of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_parcelado_value}}}

        :param saldo_disponivel_parcelado: The saldo_disponivel_parcelado of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._saldo_disponivel_parcelado = saldo_disponivel_parcelado

    @property
    def total_pagamentos(self):
        """
        Gets the total_pagamentos of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_pagamentos_value}}}

        :return: The total_pagamentos of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_pagamentos

    @total_pagamentos.setter
    def total_pagamentos(self, total_pagamentos):
        """
        Sets the total_pagamentos of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_pagamentos_value}}}

        :param total_pagamentos: The total_pagamentos of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_pagamentos = total_pagamentos

    @property
    def saldo_disponivel_parcelas(self):
        """
        Gets the saldo_disponivel_parcelas of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_parcelas_value}}}

        :return: The saldo_disponivel_parcelas of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._saldo_disponivel_parcelas

    @saldo_disponivel_parcelas.setter
    def saldo_disponivel_parcelas(self, saldo_disponivel_parcelas):
        """
        Sets the saldo_disponivel_parcelas of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_parcelas_value}}}

        :param saldo_disponivel_parcelas: The saldo_disponivel_parcelas of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._saldo_disponivel_parcelas = saldo_disponivel_parcelas

    @property
    def total_creditos_nacionais(self):
        """
        Gets the total_creditos_nacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_creditos_nacionais_value}}}

        :return: The total_creditos_nacionais of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_creditos_nacionais

    @total_creditos_nacionais.setter
    def total_creditos_nacionais(self, total_creditos_nacionais):
        """
        Sets the total_creditos_nacionais of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_creditos_nacionais_value}}}

        :param total_creditos_nacionais: The total_creditos_nacionais of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_creditos_nacionais = total_creditos_nacionais

    @property
    def total_ajustes(self):
        """
        Gets the total_ajustes of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_ajustes_value}}}

        :return: The total_ajustes of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_ajustes

    @total_ajustes.setter
    def total_ajustes(self, total_ajustes):
        """
        Sets the total_ajustes of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_ajustes_value}}}

        :param total_ajustes: The total_ajustes of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_ajustes = total_ajustes

    @property
    def total_tarifas(self):
        """
        Gets the total_tarifas of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_tarifas_value}}}

        :return: The total_tarifas of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_tarifas

    @total_tarifas.setter
    def total_tarifas(self, total_tarifas):
        """
        Sets the total_tarifas of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_tarifas_value}}}

        :param total_tarifas: The total_tarifas of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_tarifas = total_tarifas

    @property
    def total_multa(self):
        """
        Gets the total_multa of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_multa_value}}}

        :return: The total_multa of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_multa

    @total_multa.setter
    def total_multa(self, total_multa):
        """
        Sets the total_multa of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_multa_value}}}

        :param total_multa: The total_multa of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_multa = total_multa

    @property
    def saldo_disponivel_saque(self):
        """
        Gets the saldo_disponivel_saque of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_saque_value}}}

        :return: The saldo_disponivel_saque of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._saldo_disponivel_saque

    @saldo_disponivel_saque.setter
    def saldo_disponivel_saque(self, saldo_disponivel_saque):
        """
        Sets the saldo_disponivel_saque of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_saque_value}}}

        :param saldo_disponivel_saque: The saldo_disponivel_saque of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._saldo_disponivel_saque = saldo_disponivel_saque

    @property
    def total_juros(self):
        """
        Gets the total_juros of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_juros_value}}}

        :return: The total_juros of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_juros

    @total_juros.setter
    def total_juros(self, total_juros):
        """
        Sets the total_juros of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_juros_value}}}

        :param total_juros: The total_juros of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_juros = total_juros

    @property
    def saldo_pontos_fidelidade(self):
        """
        Gets the saldo_pontos_fidelidade of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_pontos_fidelidade_value}}}

        :return: The saldo_pontos_fidelidade of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._saldo_pontos_fidelidade

    @saldo_pontos_fidelidade.setter
    def saldo_pontos_fidelidade(self, saldo_pontos_fidelidade):
        """
        Sets the saldo_pontos_fidelidade of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_pontos_fidelidade_value}}}

        :param saldo_pontos_fidelidade: The saldo_pontos_fidelidade of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._saldo_pontos_fidelidade = saldo_pontos_fidelidade

    @property
    def taxa_rotativo(self):
        """
        Gets the taxa_rotativo of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_taxa_rotativo_value}}}

        :return: The taxa_rotativo of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._taxa_rotativo

    @taxa_rotativo.setter
    def taxa_rotativo(self, taxa_rotativo):
        """
        Sets the taxa_rotativo of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_taxa_rotativo_value}}}

        :param taxa_rotativo: The taxa_rotativo of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._taxa_rotativo = taxa_rotativo

    @property
    def saldo_disponivel_compra_internacional(self):
        """
        Gets the saldo_disponivel_compra_internacional of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_compra_internacional_value}}}

        :return: The saldo_disponivel_compra_internacional of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._saldo_disponivel_compra_internacional

    @saldo_disponivel_compra_internacional.setter
    def saldo_disponivel_compra_internacional(self, saldo_disponivel_compra_internacional):
        """
        Sets the saldo_disponivel_compra_internacional of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_compra_internacional_value}}}

        :param saldo_disponivel_compra_internacional: The saldo_disponivel_compra_internacional of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._saldo_disponivel_compra_internacional = saldo_disponivel_compra_internacional

    @property
    def taxa_saque(self):
        """
        Gets the taxa_saque of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_taxa_saque_value}}}

        :return: The taxa_saque of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._taxa_saque

    @taxa_saque.setter
    def taxa_saque(self, taxa_saque):
        """
        Sets the taxa_saque of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_taxa_saque_value}}}

        :param taxa_saque: The taxa_saque of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._taxa_saque = taxa_saque

    @property
    def saldo_disponivel_saque_internacional(self):
        """
        Gets the saldo_disponivel_saque_internacional of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_saque_internacional_value}}}

        :return: The saldo_disponivel_saque_internacional of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._saldo_disponivel_saque_internacional

    @saldo_disponivel_saque_internacional.setter
    def saldo_disponivel_saque_internacional(self, saldo_disponivel_saque_internacional):
        """
        Sets the saldo_disponivel_saque_internacional of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_saldo_disponivel_saque_internacional_value}}}

        :param saldo_disponivel_saque_internacional: The saldo_disponivel_saque_internacional of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._saldo_disponivel_saque_internacional = saldo_disponivel_saque_internacional

    @property
    def taxa_maxima_proximo_periodo(self):
        """
        Gets the taxa_maxima_proximo_periodo of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_taxa_maxima_proximo_periodo_value}}}

        :return: The taxa_maxima_proximo_periodo of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._taxa_maxima_proximo_periodo

    @taxa_maxima_proximo_periodo.setter
    def taxa_maxima_proximo_periodo(self, taxa_maxima_proximo_periodo):
        """
        Sets the taxa_maxima_proximo_periodo of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_taxa_maxima_proximo_periodo_value}}}

        :param taxa_maxima_proximo_periodo: The taxa_maxima_proximo_periodo of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._taxa_maxima_proximo_periodo = taxa_maxima_proximo_periodo

    @property
    def total_servicos(self):
        """
        Gets the total_servicos of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_servicos_value}}}

        :return: The total_servicos of this FaturaConsignadaDetalheResponse.
        :rtype: float
        """
        return self._total_servicos

    @total_servicos.setter
    def total_servicos(self, total_servicos):
        """
        Sets the total_servicos of this FaturaConsignadaDetalheResponse.
        {{{fatura_consignada_detalhe_response_total_servicos_value}}}

        :param total_servicos: The total_servicos of this FaturaConsignadaDetalheResponse.
        :type: float
        """
        self._total_servicos = total_servicos

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

